[tool.poetry]
name = "rosatom"
version = "0.1.0"
description = ""
authors = ["SeniorPomidorMaxim <bystrov_work@mail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
django = "^5.0.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
